---
repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: pretty-format-json
        args:
        - --autofix
    -   id: trailing-whitespace
    -   id: detect-aws-credentials
    -   id: detect-private-key
- repo: git://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.7
  hooks:
  - id: forbid-tabs
    exclude_types: [python, javascript, dtd, markdown, makefile, xml]
    exclude: binary|\.bin$
- repo: git://github.com/detailyang/pre-commit-shell
  rev: 1.0.5
  hooks:
  - id: shell-lint
- repo: git://github.com/igorshubovych/markdownlint-cli
  rev: v0.22.0
  hooks:
  -   id: markdownlint
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.25.0
  hooks:
    - id: terraform_docs
- repo: git://github.com/melmorabity/pre-commit-terraform-fmt
  rev: 0.0.1
  hooks:
    - id: terraform-fmt
- repo: git://github.com/bridgecrewio/checkov
  rev: 1.0.173
  hooks:
  - id: checkov
    files: \.tf$
